name: worf1
on: push
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4      
        - name: print a welcome message
          run: echo "Welcome to the first step"     

        - name: list files
          run: ls

        - name: read file
          run: cat 1